#!/bin/bash
if [ "$1" ]; then
	echo "configuring for PHP ${1}"
	phpize$1;
	./configure --with-php-config=/usr/bin/php-config$1
else
    echo "configuring for the default installation of php"
    phpize
    ./configure
fi

